//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneKayit.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoktorBilgileri()
        {
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int DoktorID { get; set; }
        public string DoktorAdiSoyadi { get; set; }
        public string DoktorTC { get; set; }
        public System.DateTime DoktorIseGiris { get; set; }
        public string DoktorUnvani { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
